# Generated by Django 5.1.7 on 2025-03-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedrecord',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
