# Generated by Django 5.1.7 on 2025-03-15 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
