# Generated by Django 5.1.7 on 2025-03-15 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_member_membership_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 14, 14, 8, 2, 515111, tzinfo=datetime.timezone.utc)),
        ),
    ]
