# Generated by Django 5.1.7 on 2025-03-17 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_member_membership_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 16, 8, 22, 6, 481859, tzinfo=datetime.timezone.utc)),
        ),
    ]
